### PR TITLE
Update inject.js

### PR DESCRIPTION
**Pull request by CreativeCodeCat**

### CODE REVIEW

**Comment by CreativeCodeCat** [comment]
easy fix

**Comment by Lordmau5** [comment]
Is that one line literally fixing it? O_o

Either way, if it is, it's a ... strange approach though, because that means that a Socket Connection is **required** to get the channel emotes working... which I want to avoid... :/

**Comment by CreativeCodeCat** [comment]
ya some odd reason that 1 line fixes the thing

**Comment by Lordmau5** [comment]
I believe you that it fixes it, but as I said, I'd really like to avoid a forced connection to get the channel-emotes working.

I have forwarded this issue to SirStendec (one of the FFZ devs) though - maybe it is not an issue on my side after all?

**Comment by CreativeCodeCat** [comment]
once this issues is fixed ill gladly remove the version i have running on the chrome apps just bugs the hell out of me not to be able to use it 100%

**Comment by Lordmau5** [comment]
I can feel you. Yet, since there were no more reports about this other than the one from the 30th of June, I thought it was fixed / fixed itself :/

**Comment by CreativeCodeCat** [comment]
im sorry if you feel i have "stolen" you code and just doing it behind your back its just something until yours is fixed i would of inboxed you but no way to do so on here and well since u didnt reply until u closed the last issue i thought u may be busy with something else

**Comment by Lordmau5** [comment]
It's alright.
In terms of the "stealing" thing, I just saw that you had a _seperate_ repo, and didn't fork this one - that's what was a bit annoying about it.
If you'd have forked it, I'd have known about it and could've contacted you somehow - mainly asking why you did it (and the response would've been "I'm fixing the one issue I've raised" or similar)

In regards to _inboxing_ me - Googling my nickname brings up a bunch of websites where I am:
Twitch, Twitter, Youtube, Reddit, Curseforge (Minecraft)
Twitter would've probably been the easiest in this case, but yea... Whatever :D

**Comment by CreativeCodeCat** [comment]
ya i just saw u on minecraft on a mod i downloaded today infact ill throw u a follow on twitter and twitch too

**Comment by Lordmau5** [comment]
Fixed.

**Pull request closed without merging**
